Repository Team-Picle/Picle-Client, pull requests merged in 2024-02, with the labels that each got.

#25 #22 [FEAT] 이미지 등록 기능 구현 완료
  picle/lib/models/routine_model.dart
  picle/lib/providers/image_provider.dart
  picle/lib/widgets/add_modal_widget.dart
  picle/lib/widgets/image_dialog.dart
  picle/lib/widgets/image_preview.dart
  picle/macos/Flutter/GeneratedPluginRegistrant.swift
  picle/pubspec.lock
  picle/pubspec.yaml
Labels: feat, 가은🧸

#28 #27 [MODIFY] routine_model 구조 변경
  picle/lib/data/routine_list.json
  picle/lib/main.dart
  picle/lib/models/routine_model.dart
  picle/lib/widgets/add_modal_widget.dart
  picle/lib/widgets/date_picker.dart
  picle/lib/widgets/schedule_list.dart
Labels: 희원👻, modify

#30 #26 [FEAT] 루틴 기능 구현
  picle/lib/constants/api_path.dart
  picle/lib/constants/index.dart
  picle/lib/providers/routine_provider.dart
  picle/lib/widgets/list/routine_item.dart
  picle/lib/widgets/list/routine_list.dart
Labels: feat, 희원👻

#32 #31 [FIX] RoutineItem 위젯 param에 누락된 userId 전달
  picle/lib/widgets/list/routine_list.dart
Labels: 희원👻, fix

#34 #33 [REFACTOR] 투두 API 경로 상수화
  picle/lib/constants/api_path.dart
  picle/lib/providers/todo_provider.dart
Labels: 희원👻, refactor
