Repository Team-Picle/Picle-Client, pull requests merged in 2024-03, with the labels that each got.

#36 #35 [FIX] 루틴 및 미리보기 오류 해결
  picle/ios/Podfile
  picle/ios/Podfile.lock
  picle/lib/data/preview_list.json
  picle/lib/data/todo_list.json
  picle/lib/models/preview_model.dart
  picle/lib/providers/routine_provider.dart
  picle/lib/providers/todo_provider.dart
  picle/lib/screens/main_screen.dart
  picle/lib/widgets/list/preview_item.dart
  picle/lib/widgets/list/routine_list.dart
  picle/pubspec.lock
Labels: 희원👻, fix

#39 #37 [FEAT] 미리보기 리스트 아이템 스타일링
  picle/lib/widgets/list/preview_item.dart
  picle/lib/widgets/list/routine_item.dart
  picle/lib/widgets/list/routine_list.dart
  picle/lib/widgets/list/todo_item.dart
  picle/lib/widgets/list/todo_list.dart
Labels: feat, 희원👻

#40 [FEAT] 이미 생성된 루틴은 미리보기에서 제외
  picle/ios/Flutter/Release.xcconfig
  picle/ios/Podfile.lock
  picle/lib/data/preview_list.json
  picle/lib/data/routine_list.json
  picle/lib/models/routine_model.dart
  picle/lib/providers/routine_provider.dart
  picle/lib/widgets/add_modal_widget.dart
Labels: feat, 희원👻

#42 #41 [FEAT] 누락된 루틴 기능 구현
  picle/lib/data/routine_list.json
  picle/lib/providers/routine_provider.dart
  picle/lib/widgets/list/preview_item.dart
  picle/lib/widgets/list/routine_item.dart
  picle/lib/widgets/list/routine_list.dart
Labels: feat, 희원👻

#44 #43 [FEAT] 투두 기능 수정
  picle/lib/data/todo_list.json
  picle/lib/providers/todo_provider.dart
  picle/lib/widgets/list/todo_item.dart
  picle/lib/widgets/list/todo_list.dart
Labels: feat, 희원👻

#46 #45 [FEAT] 루틴 기능 수정
  picle/lib/providers/routine_provider.dart
  picle/lib/widgets/list/routine_list.dart
Labels: feat, 희원👻

#52 #51 [FEAT] 루틴 시간 리스트에 표시
  picle/lib/data/preview_list.json
  picle/lib/data/routine_list.json
  picle/lib/models/preview_model.dart
  picle/lib/models/routine_model.dart
  picle/lib/providers/routine_provider.dart
  picle/lib/widgets/list/preview_item.dart
  picle/lib/widgets/list/routine_item.dart
  picle/lib/widgets/list/routine_list.dart
  picle/lib/widgets/routine_time.dart
Labels: feat, 희원👻

#50 #23 [FEAT] 위치 등록 기능 완료
  picle/android/app/src/main/AndroidManifest.xml
  picle/ios/Flutter/AppFrameworkInfo.plist
  picle/ios/Podfile
  picle/ios/Podfile.lock
  picle/ios/Runner.xcodeproj/project.pbxproj
  picle/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  picle/ios/Runner/AppDelegate.swift
  picle/lib/models/routine_model.dart
  picle/lib/widgets/add_modal_widget.dart
  picle/lib/widgets/gps_picker.dart
  picle/macos/Flutter/GeneratedPluginRegistrant.swift
  picle/pubspec.lock
  picle/pubspec.yaml
  picle/windows/flutter/generated_plugin_registrant.cc
  picle/windows/flutter/generated_plugins.cmake
Labels: feat, 가은🧸

#63 #54 [FEAT] 투두 수정 뷰 구현
  picle/lib/providers/todo_provider.dart
  picle/lib/widgets/list/todo_item.dart
Labels: feat, 희원👻

#68 #64 [FIX] 키보드 오버플로우 에러 해결
  picle/lib/data/todo_list.json
  picle/lib/screens/main_screen.dart
Labels: 희원👻, fix

#69 #67 [FEAT] 투두 수정 뷰에서 TextField 바깥 영역 탭하면 수정 종료
  picle/lib/widgets/list/todo_item.dart
Labels: feat, 희원👻

#70 #53 [FEAT] 루틴 시간 푸시 알림
  picle/ios/Podfile.lock
  picle/ios/Runner/AppDelegate.swift
  picle/lib/data/preview_list.json
  picle/lib/data/routine_list.json
  picle/lib/main.dart
  picle/lib/notification.dart
  picle/lib/providers/date_provider.dart
  picle/lib/providers/routine_provider.dart
  picle/lib/providers/todo_provider.dart
  picle/lib/screens/main_screen.dart
  picle/lib/widgets/calender.dart
  picle/lib/widgets/list/preview_item.dart
  picle/lib/widgets/list/routine_item.dart
  picle/lib/widgets/list/routine_list.dart
  picle/lib/widgets/list/todo_list.dart
  picle/macos/Flutter/GeneratedPluginRegistrant.swift
  picle/pubspec.lock
  picle/pubspec.yaml
Labels: feat, 희원👻

#73 #72 [FIX] 캘린더에서 날짜 선택 시 루틴 리스트 가져오기
  picle/lib/widgets/calender.dart
  picle/macos/Runner.xcodeproj/project.pbxproj
  picle/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
Labels: 희원👻, fix

#75 #74 [FIX] fetchTodoList에 누락된 코드 추가
  picle/lib/providers/todo_provider.dart
Labels: 희원👻, fix

#77 #76 [FEAT] 투두 기능 서버랑 연결
  picle/lib/constants/api_path.dart
  picle/lib/providers/todo_provider.dart
  picle/lib/widgets/list/routine_list.dart
  picle/lib/widgets/list/todo_item.dart
  picle/lib/widgets/list/todo_list.dart
Labels: feat, 희원👻

#81 #78 [FEAT] routine provider 함수 인터페이스를 네임 파라미터로 변경
  picle/lib/providers/routine_provider.dart
Labels: feat, 희원👻

#84 #61 [FEAT] 앱 아이콘 설정
  picle/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  picle/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  picle/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  picle/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  picle/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  picle/flutter_launcher_icons.yaml
  picle/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  picle/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  picle/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  picle/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  picle/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  picle/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  picle/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  picle/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  picle/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  picle/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  picle/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@1x.png
  picle/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@2x.png
  picle/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@1x.png
  picle/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@2x.png
  picle/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  picle/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  picle/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@1x.png
  picle/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@2x.png
  picle/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  picle/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  picle/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  picle/lib/icons/logo_icon.png
  picle/pubspec.lock
  picle/pubspec.yaml
Labels: feat, 희원👻

#85 #71 [FIX] 루틴 푸시 알림 에러 해결
  picle/lib/providers/routine_provider.dart
  picle/lib/widgets/list/preview_item.dart
  picle/lib/widgets/list/routine_list.dart
Labels: 희원👻, fix

#88 #78 [FEAT] 루틴 API 서버와 연결
  picle/ios/Podfile
  picle/ios/Podfile.lock
  picle/lib/constants/api_path.dart
  picle/lib/models/routine_model.dart
  picle/lib/providers/routine_provider.dart
  picle/lib/widgets/add_modal_widget.dart
  picle/lib/widgets/calender.dart
  picle/lib/widgets/list/preview_item.dart
  picle/lib/widgets/list/routine_item.dart
  picle/lib/widgets/list/routine_list.dart
Labels: feat, 희원👻

#90 #89 [STYLE] routine provider 함수들의 파라미터 포맷팅
  picle/lib/providers/routine_provider.dart
  picle/lib/widgets/list/preview_item.dart
Labels: feat, 희원👻

#97 #96 [FEAT] 투두 추가 뷰 - TextField
  picle/lib/widgets/list/todo_list.dart
Labels: feat, 희원👻

#99 #98 [FEAT] 투두 수정/삭제 모달 연결 완료
  picle/lib/widgets/list/todo_item.dart
Labels: feat, 희원👻

#100 #87 [STYLE] 캘린더 주말 데이터의 텍스트 컬러를 브랜드 컬러로 수정 & 주말의 위치 변경
  picle/lib/widgets/calender.dart
Labels: feat, 희원👻

#112 #111 [FIX] 반복 요일이 제대로 수정 안 되는 문제 해결
  picle/lib/widgets/list/preview_item.dart
Labels: 희원👻, fix

#114 #113 [FIX] 루틴 처음 수정 시 TIME이 제대로 나오지 않는 문제 수정
  picle/lib/widgets/list/preview_item.dart
Labels: 희원👻, fix

#116 #86 [FEAT] 토스트 메시지 보여주기 기능 구현
  picle/ios/Podfile.lock
  picle/lib/widgets/toast.dart
  picle/pubspec.lock
  picle/pubspec.yaml
Labels: feat, 희원👻

#123 #122 [FEAT] 루틴 등록 모달에서 필수 입력 필드 미작성 시 루틴 등록 불가 & 위치 및 이미지 등록하면 옆에 체크 …
  picle/lib/providers/routine_provider.dart
  picle/lib/widgets/list/routine_list.dart
Labels: feat, 희원👻

#125 #124 [FEAT] 루틴 인증 모달 이미지 등록 시 옆에 체크 아이콘으로 표시
  picle/lib/providers/routine_provider.dart
  picle/lib/widgets/list/routine_item.dart
  picle/lib/widgets/list/routine_list.dart
Labels: feat, 희원👻

#127 #126 [FIX] 루틴 인증 모달 널 체크 오퍼레이터 버그 해결
  picle/lib/widgets/list/routine_item.dart
Labels: 희원👻, fix

#129 #128 [FIX] time이 null일 때는 request에서 제외
  picle/lib/providers/routine_provider.dart
  picle/lib/widgets/list/routine_list.dart
Labels: 희원👻, fix

#131 #130 [FEAT] 루틴 수정 모달에서 반복 요일 선택을 repeatDays로 초기화하기
  picle/lib/widgets/list/preview_item.dart
  picle/lib/widgets/list/routine_list.dart
Labels: feat, 희원👻

#133 #132 [FIX] 투두 추가 후 TextField의 _controller.text를 빈 문자열로 초기화
  picle/lib/widgets/list/todo_list.dart
Labels: 희원👻, fix

#138 #137 [FIX] UserProvider 오류 해결
  picle/lib/app.dart
  picle/lib/login_app.dart
  picle/lib/main.dart
  picle/lib/models/user_model.dart
  picle/lib/providers/feed_provider.dart
  picle/lib/providers/routine_provider.dart
  picle/lib/providers/todo_provider.dart
  picle/lib/providers/user_provider.dart
  picle/lib/screens/login_screen.dart
  picle/lib/screens/main_screen.dart
  picle/lib/screens/my_page_screen.dart
  picle/lib/screens/social_screen.dart
  picle/lib/screens/splash_screen.dart
  picle/lib/widgets/avatar.dart
  picle/lib/widgets/calender.dart
  picle/lib/widgets/list/all_feed_item.dart
  picle/lib/widgets/list/all_feed_list.dart
  picle/lib/widgets/list/my_feed_item.dart
  picle/lib/widgets/list/my_feed_list.dart
  picle/lib/widgets/list/preview_item.dart
  picle/lib/widgets/list/routine_list.dart
  picle/lib/widgets/list/todo_item.dart
  picle/lib/widgets/list/todo_list.dart
Labels: 희원👻, fix

#144 #143 [FIX] 소셜 피드가 맨 아래에서 시작되는 오류 수정
  picle/lib/widgets/list/all_feed_list.dart
  picle/lib/widgets/list/my_feed_list.dart
Labels: 가은🧸, fix
